apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: podrunner
subjects:
- kind: ServiceAccount
  name: podrunner
  namespace: default
roleRef:
  kind: ClusterRole
  name: podrunner
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: podrunner
  namespace: default
  labels:
    k8s-app: foo
rules:
- apiGroups: [""]
  resources:
  - pods
  - services
  - logs
  verbs:
  - create
  - update
  - patch
  - delete
  - get
  - watch
  - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: podrunner
  namespace: default
  labels:
    k8s-app: foo
---
