apiVersion: v1
kind: Pod
metadata:
  labels:
    run: foo
  name: foo
  namespace: default
spec:
  containers:
  - args:
    - sleep
    - "90000"
    image: hfam/ubuntu:latest
    imagePullPolicy: IfNotPresent
    name: foo
    resources: {}
    stdin: true
    stdinOnce: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    tty: true
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-m6mv6
      readOnly: true
  restartPolicy: Never
  serviceAccountName: podrunner
  volumes:
  - name: kube-api-access-m6mv6
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
